name = input("Ingrese su nombre: ")
print(name)
print(type(name))
age = int(input("Ingrese su edad: "))
print(age)
print(type(age))
name_alt = input("Ingrese su nombre: ")
print(name_alt)
print(type(name_alt))
age_alt = float(input("Ingrese su edad: "))
print(age_alt)
print(type(age_alt))